library(tidyverse)

options(width = 200)

as_hex <- function(x) x %>% as.integer %>% as.hexmode %>% format %>% paste(collapse = "")

# read in json generated by imhex
map <- jsonlite::read_json("saves/000085_parsed.json", simplifyVector = TRUE) %>%
  .$tiles %>%
  as_tibble() %>%
  mutate(
    i = row_number() - 1,
    x = i %% width,
    y = floor(i / width),
    # buffer0_len = map_int(buffer0, length),
    # buffer1_len = map_int(buffer1, length),
    # buffer0_chr = map_chr(buffer0, as_hex),
    # buffer1_chr = map_chr(buffer1, as_hex)
  ) %>%
  select(i, x, y, everything())

map %>% filter(grepl("\\?\\?\\?", terrain)) %>% select(1:10)

table(map$buffer0_len)
table(map$buffer1_len)


map %>% 
  filter(buffer0_len > 0, !duplicated(buffer0_chr)) %>%
  select(i, x, y, terrain, feature, resource, improvement, tile_overlay_num, buffer0_len, buffer1_len, buffer0_chr) %>%
  print(n = 300)

map %>% 
  filter(buffer1_len > 0, !duplicated(buffer1_chr)) %>%
  select(i, x, y, terrain, feature, resource, improvement, tile_overlay_num, buffer0_len, buffer1_len, buffer1_chr) %>%
  print(n = 300)


map %>% 
  filter(buffer1_len > 0) %>%
  select(i, x, y, feature, improvement, tile_overlay_num, buffer0_len, buffer1_len, buffer0_chr, buffer1_chr) %>%
  print(n = 300)


map %>% 
  filter(buffer1_chr == "178a604c02000000000000000000000001000000") %>%
  select(i, x, y, terrain, feature, resource, improvement, tile_overlay_num, buffer0_len, buffer1_len, buffer0_chr, buffer1_chr) %>%
  print(n = 300)

map %>% filter(co2$bit0 > 0)


map %>% 
  filter(buffer0_len > 0, !duplicated(buffer0_chr)) %>%
  select(i, x, y, terrain, feature, resource, improvement, tile_overlay_num, buffer0_len, buffer1_len, buffer0_chr, buffer1_chr) %>%
  print(n = 300)


map %>%
  group_by(buffer0_chr, buffer1_chr) %>%
  summarise(
    # terrain = paste(unique(terrain), collapse = ", "),
    feature = paste(unique(feature), collapse = ", "),
    resource = paste(unique(resource), collapse = ", "),
    improvement = paste(unique(improvement), collapse = ", "),
    tile_overlay_num = paste(unique(tile_overlay_num), collapse = ", "),
    tile_overlay_num = paste(unique(tile_overlay_num), collapse = ", "),
  )
